<a href="https://colab.research.google.com/github/jpgill86/python-for-neuroscientists/blob/master/notebooks/03-Essential-Packages.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5, 6])
x

array([1, 2, 3, 4, 5, 6])

In [3]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [4]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
np.ones((2, 3)) * 7

array([[7., 7., 7.],
       [7., 7., 7.]])

In [6]:
x = np.arange(6)
y = np.ones(6) * 7

# element-wise multiplication
print(x * y)

# matrix multiplication (dot product in this case)
print(x.dot(y))

[ 0.  7. 14. 21. 28. 35.]
105.0


# SciPy

# pandas

In [7]:
import pandas as pd

# matplotlib and seaborn

In [8]:
import matplotlib.pyplot as plt
import seaborn as sns

# Continue to the Next Lesson

Return to home to continue to the next lession:

https://jpgill86.github.io/python-for-neuroscientists/

# External Resources

Documentation:

* [NumPy manual](https://numpy.org/doc/stable/)
* [NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)
* [NumPy tutorials](https://numpy.org/doc/stable/user/tutorials_index.html)
* [NumPy for Matlab users](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)
* [SciPy reference guide](https://docs.scipy.org/doc/scipy/reference/)
* [pandas documentation](https://pandas.pydata.org/docs/)

Free interactive book created by Jake VanderPlas:

* [Python Data Science Handbook](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/Index.ipynb)

# License

[This work](https://github.com/jpgill86/python-for-neuroscientists) is licensed under a [Creative Commons Attribution 4.0 International
License](http://creativecommons.org/licenses/by/4.0/).